INSERT INTO breed (name) VALUES ('Labrador Retriever');
INSERT INTO breed (name) VALUES ('German Shepherd');
INSERT INTO breed (name) VALUES ('Golden Retriever');
INSERT INTO breed (name) VALUES ('French Bulldog');
INSERT INTO breed (name) VALUES ('Bulldog');
INSERT INTO breed (name) VALUES ('Poodle');
INSERT INTO breed (name) VALUES ('Beagle');
INSERT INTO breed (name) VALUES ('Rottweiler');
INSERT INTO breed (name) VALUES ('Yorkshire Terrier');
INSERT INTO breed (name) VALUES ('Boxer');
INSERT INTO breed (name) VALUES ('Dachshund');
INSERT INTO breed (name) VALUES ('Pembroke Welsh Corgi');
INSERT INTO breed (name) VALUES ('Siberian Husky');
INSERT INTO breed (name) VALUES ('Doberman Pinscher');
INSERT INTO breed (name) VALUES ('Australian Shepherd');
INSERT INTO breed (name) VALUES ('Shih Tzu');
INSERT INTO breed (name) VALUES ('Chihuahua');
INSERT INTO breed (name) VALUES ('Great Dane');
INSERT INTO breed (name) VALUES ('Border Collie');
INSERT INTO breed (name) VALUES ('Cocker Spaniel');
INSERT INTO breed (name) VALUES ('Boston Terrier');
INSERT INTO breed (name) VALUES ('Miniature Schnauzer');
INSERT INTO breed (name) VALUES ('Pug');
INSERT INTO breed (name) VALUES ('Shetland Sheepdog');
INSERT INTO breed (name) VALUES ('Bichon Frise');
INSERT INTO breed (name) VALUES ('Akita');
INSERT INTO breed (name) VALUES ('St. Bernard');
INSERT INTO breed (name) VALUES ('Bull Terrier');
INSERT INTO breed (name) VALUES ('Havanese');
INSERT INTO breed (name) VALUES ('Scottish Terrier');
INSERT INTO breed (name) VALUES ('Newfoundland');
INSERT INTO breed (name) VALUES ('Maltese');
INSERT INTO breed (name) VALUES ('Weimaraner');
INSERT INTO breed (name) VALUES ('Pekingese');
INSERT INTO breed (name) VALUES ('Bloodhound');
INSERT INTO breed (name) VALUES ('Basenji');
INSERT INTO breed (name) VALUES ('Belgian Malinois');
INSERT INTO breed (name) VALUES ('Airedale Terrier');
INSERT INTO breed (name) VALUES ('Irish Setter');
INSERT INTO breed (name) VALUES ('Samoyed');
INSERT INTO breed (name) VALUES ('English Springer Spaniel');
INSERT INTO breed (name) VALUES ('Jack Russell Terrier');
INSERT INTO breed (name) VALUES ('Old English Sheepdog');
INSERT INTO breed (name) VALUES ('Lhasa Apso');
INSERT INTO breed (name) VALUES ('Whippet');
INSERT INTO breed (name) VALUES ('Vizsla');
INSERT INTO breed (name) VALUES ('Chesapeake Bay Retriever');
INSERT INTO breed (name) VALUES ('Italian Greyhound');
INSERT INTO breed (name) VALUES ('Norfolk Terrier');
INSERT INTO breed (name) VALUES ('Cane Corso');
INSERT INTO breed (name) VALUES ('Chinese Shar-Pei');
INSERT INTO breed (name) VALUES ('Collie');
INSERT INTO breed (name) VALUES ('Flat-Coated Retriever');
