INSERT INTO breed (name) VALUE ('Labrador Retriever');
INSERT INTO breed (name) VALUE ('German Shepherd');
INSERT INTO breed (name) VALUE ('Golden Retriever');
INSERT INTO breed (name) VALUE ('French Bulldog');
INSERT INTO breed (name) VALUE ('Bulldog');
INSERT INTO breed (name) VALUE ('Poodle');
INSERT INTO breed (name) VALUE ('Beagle');
INSERT INTO breed (name) VALUE ('Rottweiler');
INSERT INTO breed (name) VALUE ('Yorkshire Terrier');
INSERT INTO breed (name) VALUE ('Boxer');
INSERT INTO breed (name) VALUE ('Dachshund');
INSERT INTO breed (name) VALUE ('Pembroke Welsh Corgi');
INSERT INTO breed (name) VALUE ('Siberian Husky');
INSERT INTO breed (name) VALUE ('Doberman Pinscher');
INSERT INTO breed (name) VALUE ('Australian Shepherd');
INSERT INTO breed (name) VALUE ('Shih Tzu');
INSERT INTO breed (name) VALUE ('Chihuahua');
INSERT INTO breed (name) VALUE ('Great Dane');
INSERT INTO breed (name) VALUE ('Border Collie');
INSERT INTO breed (name) VALUE ('Cocker Spaniel');
INSERT INTO breed (name) VALUE ('Boston Terrier');
INSERT INTO breed (name) VALUE ('Miniature Schnauzer');
INSERT INTO breed (name) VALUE ('Pug');
INSERT INTO breed (name) VALUE ('Shetland Sheepdog');
INSERT INTO breed (name) VALUE ('Bichon Frise');
INSERT INTO breed (name) VALUE ('Akita');
INSERT INTO breed (name) VALUE ('St. Bernard');
INSERT INTO breed (name) VALUE ('Bull Terrier');
INSERT INTO breed (name) VALUE ('Havanese');
INSERT INTO breed (name) VALUE ('Scottish Terrier');
INSERT INTO breed (name) VALUE ('Newfoundland');
INSERT INTO breed (name) VALUE ('Maltese');
INSERT INTO breed (name) VALUE ('Weimaraner');
INSERT INTO breed (name) VALUE ('Pekingese');
INSERT INTO breed (name) VALUE ('Bloodhound');
INSERT INTO breed (name) VALUE ('Basenji');
INSERT INTO breed (name) VALUE ('Belgian Malinois');
INSERT INTO breed (name) VALUE ('Airedale Terrier');
INSERT INTO breed (name) VALUE ('Irish Setter');
INSERT INTO breed (name) VALUE ('Samoyed');
INSERT INTO breed (name) VALUE ('English Springer Spaniel');
INSERT INTO breed (name) VALUE ('Jack Russell Terrier');
INSERT INTO breed (name) VALUE ('Old English Sheepdog');
INSERT INTO breed (name) VALUE ('Lhasa Apso');
INSERT INTO breed (name) VALUE ('Whippet');
INSERT INTO breed (name) VALUE ('Vizsla');
INSERT INTO breed (name) VALUE ('Chesapeake Bay Retriever');
INSERT INTO breed (name) VALUE ('Italian Greyhound');
INSERT INTO breed (name) VALUE ('Norfolk Terrier');
INSERT INTO breed (name) VALUE ('Cane Corso');
INSERT INTO breed (name) VALUE ('Chinese Shar-Pei');
INSERT INTO breed (name) VALUE ('Collie');
INSERT INTO breed (name) VALUE ('Flat-Coated Retriever');
